# This file was generated by GoReleaser. DO NOT EDIT.
cask "envy" do
  name "envy"
  desc ""
  homepage ""
  version "0.1.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envy"

  on_macos do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "521989b42d4e7f0f55eefb14ce809ec7354b6f1e73dc2378250a0bf357d41132"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "72be254dd18cd0119bb545926101cffd0d75ce94e04f99bedc65549273070632"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "cc78aec9498c6ad77297e5621b4ea06437ecdca6c554809baa143ea76af61d0c"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "ad38074ae422b1874276fa47ee2b38d8eafd3158f788bc570261f52114b79862"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envy"]
    end
  end

  # No zap stanza required
end
