# This file was generated by GoReleaser. DO NOT EDIT.
cask "envy" do
  name "envy"
  desc ""
  homepage ""
  version "0.1.28"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envy"

  on_macos do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "f4507177c0533fe791fe0ee7d3264c84600da580ffbb3a75721e60b5c97f4c35"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "5a52c7be0dfc0ceeea277488da95d004a5f66f631a426d2e6f67a9ba907a1025"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "d01b4763f7e51822306c83040220cb90461a6eb6649bdc013ea823f75643986a"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "651b15a98325db40cc71985f5e6035689b7553c51c64db4aa7a3f6b396932d1e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envy"]
    end
  end

  # No zap stanza required
end
