# This file was generated by GoReleaser. DO NOT EDIT.
cask "envy" do
  name "envy"
  desc ""
  homepage ""
  version "0.1.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envy"

  on_macos do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "42199cd2aa2e7ce35f01b1749f1fe6b84943062b218789b20b60b251f0acb949"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Darwin_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "dc6dd4c272cbfd2e4e39806557d03762f0e16dd53d32ef27099840539bd7ae2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_x86_64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "b18e8a33b2bdf93f45891ff7f7cd00f6971a0029a9777e038b265e4eea4d775d"
    end
    on_arm do
      url "https://github.com/front-matter/envy/releases/download/v#{version}/envy_Linux_arm64.tar.gz",
        verified: "github.com/front-matter/envy"
      sha256 "f09190312d3f230611260fe8d4cf38176b0216b054ebbb6266e082aa058e837d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envy"]
    end
  end

  # No zap stanza required
end
